name: im
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/portraits/

  fonts:
    - family: OptimaNova
      fonts:
        - asset: assets/fonts/optima_nova_black.ttf
          weight: 900
    - family: Bangers
      fonts:
        - asset: fonts/Bangers/Bangers-Regular.ttf
    - family: Boogaloo
      fonts:
        - asset: fonts/Boogaloo/Boogaloo-Regular.ttf
    - family: PermanentMarker
      fonts:
        - asset: fonts/Permanent_Marker/PermanentMarker-Regular.ttf
